// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    ElButton: typeof import('element-plus/es')['ElButton']
    ElButtonGroup: typeof import('element-plus/es')['ElButtonGroup']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElFooter: typeof import('element-plus/es')['ElFooter']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElResult: typeof import('element-plus/es')['ElResult']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    EnProcess: typeof import('./components/EnProcess.md')['default']
    IAkarIconsGithubFill: typeof import('~icons/akar-icons/github-fill')['default']
    ILaLanguage: typeof import('~icons/la/language')['default']
    IMdiContentDuplicate: typeof import('~icons/mdi/content-duplicate')['default']
    IMdiHomeSearchOutline: typeof import('~icons/mdi/home-search-outline')['default']
    IPhCloudMoonBold: typeof import('~icons/ph/cloud-moon-bold')['default']
    IPhSunHorizonBold: typeof import('~icons/ph/sun-horizon-bold')['default']
    IRiArticleLine: typeof import('~icons/ri/article-line')['default']
    TheFooter: typeof import('./components/TheFooter.vue')['default']
    TheHeader: typeof import('./components/TheHeader.vue')['default']
    ZhProcess: typeof import('./components/ZhProcess.md')['default']
  }
}

export { }
